on: [push]

name: build

jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2.4.0

    - name: Build Docker Images
      uses: philips-software/docker-ci-scripts@v4.1.0
      with:
        dockerfile: 0/alpine
        image-name: goss
        tags: latest 0.3 0.3.7 0.3.7.alpine
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: philipssoftware
        GITHUB_ORGANIZATION: philips-software
